from collections import namedtuple


Assignment = namedtuple('Assignment', 'name expr')
Attribute = namedtuple('Attribute', 'name type expr')
BinaryOperation = namedtuple('BinaryOperation', 'operator left right')
Block = namedtuple('Block', 'elements')
Case = namedtuple('Case', 'expr typeactions')
Formal = namedtuple('Formal', 'name type')
FunctionCall = namedtuple('FunctionCall', 'name params')
Ident = namedtuple('Ident', 'name')
If = namedtuple('If', 'condition true false')
Let = namedtuple('Let', 'assignments expr')
MethodCall = namedtuple('MethodCall', 'object targettype method')
Method = namedtuple('Method', 'name type formals expr')
New = namedtuple('New', 'type')
Type = namedtuple('Type', 'name inherits features')
TypeAction = namedtuple('TypeAction', 'name type expr')
UnaryOperation = namedtuple('UnaryOperation', 'operator right')
While = namedtuple('While', 'condition action')
